apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-server
  template:
    metadata:
      labels:
        app: music-server
    spec:
      containers:
      - name: music-server
        image: masapath/music-share-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://music-db:5432/musicdb
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: music-server
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
  selector:
    app: music-server
