apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-db
  template:
    metadata:
      labels:
        app: music-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: musicdb
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: music-db-storage
      volumes:
      - name: music-db-storage
        persistentVolumeClaim:
          claimName: music-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: music-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: music-db
